In [267]:
import pandas as pd 

data = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

print(data.head(5))

   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract Pape

In [268]:
print(data.shape)

(7043, 21)


In [269]:
data.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [270]:
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   str    
 1   gender            7043 non-null   str    
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   str    
 4   Dependents        7043 non-null   str    
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   str    
 7   MultipleLines     7043 non-null   str    
 8   InternetService   7043 non-null   str    
 9   OnlineSecurity    7043 non-null   str    
 10  OnlineBackup      7043 non-null   str    
 11  DeviceProtection  7043 non-null   str    
 12  TechSupport       7043 non-null   str    
 13  StreamingTV       7043 non-null   str    
 14  StreamingMovies   7043 non-null   str    
 15  Contract          7043 non-null   str    
 16  PaperlessBilling  7043 non-null   str    
 17  Paymen

In [271]:
data["TotalCharges"] = pd.to_numeric(data["TotalCharges"], errors="coerce")

In [272]:
data = data.drop("customerID", axis=1)

In [273]:
numerical = data.select_dtypes(include="number").columns
categorical = data.select_dtypes(include=["string","object"]).columns

print(numerical)
print(categorical)

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')
Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'Churn'],
      dtype='str')


In [274]:
for cols in numerical:
    print(f"\nSkewness Values Of {cols}")
    print(data[cols].skew())


Skewness Values Of SeniorCitizen
1.8336327440928564

Skewness Values Of tenure
0.2395397495619829

Skewness Values Of MonthlyCharges
-0.22052443394398033

Skewness Values Of TotalCharges
0.961642499724251


In [275]:
for cols in categorical:
    print(f"\nUnique Values Of {cols}")
    print(data[cols].unique())


Unique Values Of gender
<ArrowStringArray>
['Female', 'Male']
Length: 2, dtype: str

Unique Values Of Partner
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

Unique Values Of Dependents
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

Unique Values Of PhoneService
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

Unique Values Of MultipleLines
<ArrowStringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str

Unique Values Of InternetService
<ArrowStringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

Unique Values Of OnlineSecurity
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

Unique Values Of OnlineBackup
<ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

Unique Values Of DeviceProtection
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

Unique Values Of TechSupport
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

Unique Valu

In [276]:
data["gender"] = data["gender"].map({"Female":0, "Male":1})

In [277]:
binary_cols = [
    "Partner",
    "Dependents",
    "PhoneService",
    "PaperlessBilling",

]

data[binary_cols] = data[binary_cols].replace({
    "Yes": 1,
    "No": 0
})

In [278]:
data["Churn"] = data["Churn"].replace({
    "No": 0,
    "Yes": 1
})

In [279]:
data.head(5)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0
1,1,0,0,0,34,1,No,DSL,Yes,No,Yes,No,No,No,One year,0,Mailed check,56.95,1889.50,0
2,1,0,0,0,2,1,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1
3,1,0,0,0,45,0,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,0,0,0,0,2,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1


In [280]:
data["TotalCharges"] = data["TotalCharges"].fillna(data["TotalCharges"].median())

In [281]:
categorical_cols = [
    "MultipleLines",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "PaymentMethod"
]    

ordinal_cols = [
    "Contract"
]


numerical_cols = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

In [282]:
X = data.drop("Churn",axis=1)
y = data["Churn"]

In [283]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state = 42,
    stratify = y
)

In [284]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder,OrdinalEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer([
    ("num", StandardScaler(), numerical_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
    ("ord", OrdinalEncoder(), ordinal_cols),
    ("bin", "passthrough",binary_cols)
])

In [285]:
X_train_scaled = preprocessor.fit_transform(X_train)
X_test_scaled = preprocessor.transform(X_test)

In [286]:
print(y.value_counts())

Churn
0    5174
1    1869
Name: count, dtype: int64


In [287]:
print(y_train.unique())
print(y_train.dtype)
print(y_train.value_counts())

[0 1]
object
Churn
0    4139
1    1495
Name: count, dtype: int64


In [288]:
y_train = y_train.astype(int)

In [289]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train_scaled,
    y_train
)

In [290]:
X_train_smote[:5]


array([[ 0.10237124, -0.52197565, -0.26328906,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [-0.71174346,  0.33747781, -0.50481448,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         1.        ,  1.        ,  0.        ],
       [-0.79315493, -0.8090

In [291]:
y_train_smote[:5]

0    0
1    0
2    0
3    0
4    0
Name: Churn, dtype: int64

In [292]:
X_test_scaled[:5]

array([[1.6084834273893616, 1.6299763471022684, 2.7076141006572096, 0.0,
        0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 2.0, 1, 1,
        1, 1],
       [-0.9966836022806536, 1.1687252637656007, -0.6115054067174635,
        0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        0, 0, 1, 1],
       [0.346605647392948, 0.44532428414406383, 0.399489881907842, 0.0,
        0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0,
        0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1, 1,
        1, 1],
       [-0.5896262538947137, 0.44034675446776916, -0.36554550804076646,
        1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
        0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        1, 0, 1, 0],
       [1.6084834273893616, 0.5880134681978536, 1.58852

## Logistic Regression

In [293]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    random_state =42
)

model.fit(X_train_smote, y_train_smote)

,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",42
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solve

In [294]:
y_pred = model.predict(X_test_scaled)



In [295]:
import numpy as np

In [296]:
print("y_train:", y_train.dtype, y_train.unique())
print("y_test:", y_test.dtype, y_test.unique())
print("y_pred:", y_pred.dtype, np.unique(y_pred))

y_train: int64 [0 1]
y_test: object [0 1]
y_pred: int64 [0 1]


In [297]:
y_test = y_test.astype(int)

In [298]:
from sklearn.metrics import accuracy_score, precision_score, f1_score, classification_report, confusion_matrix

In [299]:
print("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.7352732434350603


ROC-AUC = 0.84

Your ROC-AUC of 0.8398 indicates that the model has fairly strong ability to distinguish the two classes across different classification thresholds.

So don't look at your 73.5% accuracy and conclude that the model is poor. Your class imbalance and use of SMOTE make the other metrics particularly important.

What I'd d

In [300]:
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score
)

print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("ROC-AUC:", roc_auc_score(y_test, model.predict_proba(X_test_scaled)[:, 1]))

              precision    recall  f1-score   support

           0       0.90      0.72      0.80      1035
           1       0.50      0.79      0.61       374

    accuracy                           0.74      1409
   macro avg       0.70      0.75      0.71      1409
weighted avg       0.80      0.74      0.75      1409

Confusion Matrix:
[[742 293]
 [ 80 294]]
ROC-AUC: 0.8397762794182232


## KNN Classifier

In [301]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train_smote, y_train_smote)

y_pred_knn = knn.predict(X_test_scaled)

In [302]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

print("Accuracy:", accuracy_score(y_test, y_pred_knn))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_knn))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_knn))

print("\nROC-AUC:",
      roc_auc_score(y_test, knn.predict_proba(X_test_scaled)[:, 1]))

Accuracy: 0.6827537260468417

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.68      0.76      1035
           1       0.44      0.68      0.53       374

    accuracy                           0.68      1409
   macro avg       0.65      0.68      0.65      1409
weighted avg       0.74      0.68      0.70      1409


Confusion Matrix:
[[707 328]
 [119 255]]

ROC-AUC: 0.7608876488671885


## Decision Tree Classifier

In [303]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train_smote, y_train_smote)

y_pred_dt = dt.predict(X_test_scaled)

In [304]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

print("Accuracy:", accuracy_score(y_test, y_pred_dt))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_dt))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))

print("\nROC-AUC:",
      roc_auc_score(
          y_test,
          dt.predict_proba(X_test_scaled)[:, 1]
      ))

Accuracy: 0.7154009936124911

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.78      0.80      1035
           1       0.47      0.54      0.50       374

    accuracy                           0.72      1409
   macro avg       0.65      0.66      0.65      1409
weighted avg       0.73      0.72      0.72      1409


Confusion Matrix:
[[806 229]
 [172 202]]

ROC-AUC: 0.6589811155028547


## Random Forest 🌲🌲🌲

In [305]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train_smote, y_train_smote)

y_pred_rf = rf.predict(X_test_scaled)

In [306]:
print("Accuracy:", accuracy_score(y_test, y_pred_rf))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

print("\nROC-AUC:",
      roc_auc_score(
          y_test,
          rf.predict_proba(X_test_scaled)[:, 1]
      ))

Accuracy: 0.7672107877927609

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.85      0.84      1035
           1       0.56      0.55      0.56       374

    accuracy                           0.77      1409
   macro avg       0.70      0.70      0.70      1409
weighted avg       0.77      0.77      0.77      1409


Confusion Matrix:
[[876 159]
 [169 205]]

ROC-AUC: 0.8110129427264977


## Gradient Boosting 🚀

In [307]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(random_state=42)

gb.fit(X_train_smote, y_train_smote)

y_pred_gb = gb.predict(X_test_scaled)

In [308]:
print("Accuracy:", accuracy_score(y_test, y_pred_gb))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_gb))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_gb))

print("\nROC-AUC:",
      roc_auc_score(
          y_test,
          gb.predict_proba(X_test_scaled)[:, 1]
      ))

Accuracy: 0.7693399574166075

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.79      0.83      1035
           1       0.55      0.70      0.62       374

    accuracy                           0.77      1409
   macro avg       0.72      0.75      0.73      1409
weighted avg       0.79      0.77      0.78      1409


Confusion Matrix:
[[822 213]
 [112 262]]

ROC-AUC: 0.8404479578392622


## XGBoost

In [309]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

xgb.fit(X_train_smote, y_train_smote)

y_pred_xgb = xgb.predict(X_test_scaled)

In [310]:
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_xgb))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))

print("\nROC-AUC:",
      roc_auc_score(
          y_test,
          xgb.predict_proba(X_test_scaled)[:, 1]
      ))

Accuracy: 0.7743080198722498

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.83      0.84      1035
           1       0.57      0.62      0.59       374

    accuracy                           0.77      1409
   macro avg       0.71      0.73      0.72      1409
weighted avg       0.78      0.77      0.78      1409


Confusion Matrix:
[[858 177]
 [141 233]]

ROC-AUC: 0.8182476943346508


| Model               |   Accuracy | Churn Precision | Churn Recall | Churn F1 |   ROC-AUC |
| ------------------- | ---------: | --------------: | -----------: | -------: | --------: |
| Logistic Regression |     73.53% |            0.50 |     **0.79** |     0.61 | **0.840** |
| KNN                 |     68.28% |            0.44 |         0.68 |     0.53 |     0.761 |
| Decision Tree       |     71.54% |            0.47 |         0.54 |     0.50 |     0.659 |
| Random Forest       |     76.72% |            0.56 |         0.55 |     0.56 |     0.811 |
| Gradient Boosting   |     76.93% |            0.55 |     **0.70** | **0.62** | **0.840** |
| **XGBoost**         | **77.43%** |        **0.57** |         0.62 |     0.59 |     0.818 |


# <>

# Hyperparameter Tuning For All The Model

### Random Forest Classifier

In [315]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import pandas as pd
best_f1 = float("-inf")
best_params = None
n_estimators_values = [100, 200, 300]
max_depth_values = [5, 10, 15, None]
min_samples_split_values = [2, 5, 10]
min_samples_leaf_values = [1, 2, 4]
max_features_values = ["sqrt", "log2"]


for n_estimators in n_estimators_values:

    for max_depth in max_depth_values:

        for min_samples_split in min_samples_split_values:

            for min_samples_leaf in min_samples_leaf_values:

                for max_features in max_features_values:

                    rf = RandomForestClassifier(
                        n_estimators=n_estimators,
                        max_depth=max_depth,
                        min_samples_split=min_samples_split,
                        min_samples_leaf=min_samples_leaf,
                        max_features=max_features,
                        random_state=42,
                        n_jobs=-1
                    )

                    rf.fit(X_train_smote, y_train_smote)

                    y_pred = rf.predict(X_test_scaled)

                    f1 = f1_score(y_test, y_pred)
                    if f1 > best_f1:
                        best_f1 = f1

                        best_params ={
                            "n_estimators": n_estimators,
                            "max_depth": max_depth,
                            "min_samples_split": min_samples_split,
                            "min_samples_leaf": min_samples_leaf,
                            "max_features": max_features,
                          }

                        print(
                            "n_estimators : ", n_estimators,
                            "max_depth : ", max_depth,
                            "min_samples_split : ", min_samples_split,
                            "min_samples_leaf : ", min_samples_leaf,
                            "max_features : ", max_features,
                        )

print("Best F1 : ", best_f1) 
print("Best Params : ", best_params)                       

n_estimators :  100 max_depth :  5 min_samples_split :  2 min_samples_leaf :  1 max_features :  sqrt
n_estimators :  100 max_depth :  5 min_samples_split :  2 min_samples_leaf :  2 max_features :  sqrt
n_estimators :  100 max_depth :  5 min_samples_split :  2 min_samples_leaf :  4 max_features :  sqrt
n_estimators :  200 max_depth :  5 min_samples_split :  10 min_samples_leaf :  4 max_features :  sqrt
Best F1 :  0.6182965299684543
Best Params :  {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 'sqrt'}


In [316]:
best_rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=5,
    min_samples_split=10,
    min_samples_leaf=4,
    max_features="sqrt",
    random_state=42,
    n_jobs=-1
)

best_rf.fit(X_train_smote, y_train_smote)

y_pred_best_rf = best_rf.predict(X_test_scaled)
y_prob_best_rf = best_rf.predict_proba(X_test_scaled)[:, 1]

In [317]:
print("Accuracy:",
      accuracy_score(y_test, y_pred_best_rf))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_best_rf))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_best_rf))

print("\nROC-AUC:",
      roc_auc_score(y_test, y_prob_best_rf))

Accuracy: 0.7423704755145494

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.73      0.81      1035
           1       0.51      0.79      0.62       374

    accuracy                           0.74      1409
   macro avg       0.71      0.76      0.71      1409
weighted avg       0.80      0.74      0.76      1409


Confusion Matrix:
[[752 283]
 [ 80 294]]

ROC-AUC: 0.8337363403859568


## Tune Gradient Boosting

In [318]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import f1_score

best_f1 = float("-inf")
best_params = None

n_estimators_values = [50, 100, 150, 200]
learning_rate_values = [0.05, 0.1, 0.2]
max_depth_values = [2, 3, 5]
min_samples_split_values = [2, 5, 10]
min_samples_leaf_values = [1, 2, 4]


for n_estimators in n_estimators_values:

    for learning_rate in learning_rate_values:

        for max_depth in max_depth_values:

            for min_samples_split in min_samples_split_values:

                for min_samples_leaf in min_samples_leaf_values:

                    gb = GradientBoostingClassifier(
                        n_estimators=n_estimators,
                        learning_rate=learning_rate,
                        max_depth=max_depth,
                        min_samples_split=min_samples_split,
                        min_samples_leaf=min_samples_leaf,
                        random_state=42
                    )

                    gb.fit(X_train_smote, y_train_smote)

                    y_pred = gb.predict(X_test_scaled)

                    f1 = f1_score(y_test, y_pred)

                    if f1 > best_f1:

                        best_f1 = f1

                        best_params = {
                            "n_estimators": n_estimators,
                            "learning_rate": learning_rate,
                            "max_depth": max_depth,
                            "min_samples_split": min_samples_split,
                            "min_samples_leaf": min_samples_leaf
                        }

                        print(
                            "n_estimators : ", n_estimators,
                            "learning_rate : ", learning_rate,
                            "max_depth : ", max_depth,
                            "min_samples_split : ", min_samples_split,
                            "min_samples_leaf : ", min_samples_leaf
                        )


print("Best F1 : ", best_f1)
print("Best Params : ", best_params)

n_estimators :  50 learning_rate :  0.05 max_depth :  2 min_samples_split :  2 min_samples_leaf :  1
n_estimators :  50 learning_rate :  0.05 max_depth :  3 min_samples_split :  2 min_samples_leaf :  1
n_estimators :  50 learning_rate :  0.05 max_depth :  5 min_samples_split :  2 min_samples_leaf :  2
n_estimators :  50 learning_rate :  0.05 max_depth :  5 min_samples_split :  2 min_samples_leaf :  4
n_estimators :  50 learning_rate :  0.05 max_depth :  5 min_samples_split :  10 min_samples_leaf :  4
n_estimators :  50 learning_rate :  0.1 max_depth :  5 min_samples_split :  2 min_samples_leaf :  1
n_estimators :  50 learning_rate :  0.2 max_depth :  2 min_samples_split :  2 min_samples_leaf :  1
n_estimators :  100 learning_rate :  0.1 max_depth :  2 min_samples_split :  2 min_samples_leaf :  1
n_estimators :  100 learning_rate :  0.1 max_depth :  2 min_samples_split :  2 min_samples_leaf :  2
Best F1 :  0.6312217194570136
Best Params :  {'n_estimators': 100, 'learning_rate': 0.1, 'ma

In [319]:
best_gb = GradientBoostingClassifier(
    n_estimators=best_params["n_estimators"],
    learning_rate=best_params["learning_rate"],
    max_depth=best_params["max_depth"],
    min_samples_split=best_params["min_samples_split"],
    min_samples_leaf=best_params["min_samples_leaf"],
    random_state=42
)

best_gb.fit(X_train_smote, y_train_smote)

y_pred_best_gb = best_gb.predict(X_test_scaled)

In [320]:
print("Accuracy:", accuracy_score(y_test, y_pred_best_gb))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_best_gb))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_best_gb))

print("\nROC-AUC:",
      roc_auc_score(
          y_test,
          best_gb.predict_proba(X_test_scaled)[:, 1]
      ))

Accuracy: 0.7686302342086586

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.78      0.83      1035
           1       0.55      0.75      0.63       374

    accuracy                           0.77      1409
   macro avg       0.72      0.76      0.73      1409
weighted avg       0.80      0.77      0.78      1409


Confusion Matrix:
[[804 231]
 [ 95 279]]

ROC-AUC: 0.8403058720194271


| Metric          | Baseline GB |   Tuned GB |  Change |
| --------------- | ----------: | ---------: | ------: |
| Accuracy        |      76.93% | **76.86%** | ↓ 0.07% |
| Churn Precision |        0.55 |   **0.55** |       — |
| Churn Recall    |        0.70 |   **0.75** |  ↑ 0.05 |
| Churn F1        |        0.62 |   **0.63** |  ↑ 0.01 |
| ROC-AUC         |      0.8404 | **0.8403** |  ≈ same |


# XGBoost tuning

In [321]:
from xgboost import XGBClassifier
from sklearn.metrics import f1_score

best_f1 = float("-inf")
best_params = None

n_estimators_values = [100, 200, 300]
learning_rate_values = [0.05, 0.1, 0.2]
max_depth_values = [3, 5, 7]
min_child_weight_values = [1, 3, 5]
subsample_values = [0.8, 1.0]

for n_estimators in n_estimators_values:
    for learning_rate in learning_rate_values:
        for max_depth in max_depth_values:
            for min_child_weight in min_child_weight_values:
                for subsample in subsample_values:

                    xgb = XGBClassifier(
                        n_estimators=n_estimators,
                        learning_rate=learning_rate,
                        max_depth=max_depth,
                        min_child_weight=min_child_weight,
                        subsample=subsample,
                        random_state=42,
                        eval_metric="logloss",
                        n_jobs=-1
                    )

                    xgb.fit(
                        X_train_smote,
                        y_train_smote
                    )

                    y_pred = xgb.predict(X_test_scaled)

                    f1 = f1_score(
                        y_test,
                        y_pred
                    )

                    if f1 > best_f1:

                        best_f1 = f1

                        best_params = {
                            "n_estimators": n_estimators,
                            "learning_rate": learning_rate,
                            "max_depth": max_depth,
                            "min_child_weight": min_child_weight,
                            "subsample": subsample
                        }

                        print(
                            "n_estimators : ", n_estimators,
                            "learning_rate : ", learning_rate,
                            "max_depth : ", max_depth,
                            "min_child_weight : ", min_child_weight,
                            "subsample : ", subsample
                        )

print("Best F1 : ", best_f1)
print("Best Params : ", best_params)

n_estimators :  100 learning_rate :  0.05 max_depth :  3 min_child_weight :  1 subsample :  0.8
n_estimators :  100 learning_rate :  0.05 max_depth :  3 min_child_weight :  3 subsample :  0.8
n_estimators :  100 learning_rate :  0.05 max_depth :  5 min_child_weight :  3 subsample :  0.8
n_estimators :  300 learning_rate :  0.05 max_depth :  3 min_child_weight :  1 subsample :  0.8
n_estimators :  300 learning_rate :  0.05 max_depth :  3 min_child_weight :  5 subsample :  0.8
Best F1 :  0.6328502415458938
Best Params :  {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 3, 'min_child_weight': 5, 'subsample': 0.8}


In [322]:
best_xgb = XGBClassifier(
    n_estimators=best_params["n_estimators"],
    learning_rate=best_params["learning_rate"],
    max_depth=best_params["max_depth"],
    min_child_weight=best_params["min_child_weight"],
    subsample=best_params["subsample"],
    random_state=42,
    eval_metric="logloss",
    n_jobs=-1
)

best_xgb.fit(X_train_smote, y_train_smote)

y_pred_best_xgb = best_xgb.predict(X_test_scaled)

In [323]:
print("Accuracy:", accuracy_score(y_test, y_pred_best_xgb))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_best_xgb))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_best_xgb))

print("\nROC-AUC:",
      roc_auc_score(
          y_test,
          best_xgb.predict_proba(X_test_scaled)[:, 1]
      ))

Accuracy: 0.7842441447835344

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.81      0.85      1035
           1       0.58      0.70      0.63       374

    accuracy                           0.78      1409
   macro avg       0.73      0.76      0.74      1409
weighted avg       0.80      0.78      0.79      1409


Confusion Matrix:
[[843 192]
 [112 262]]

ROC-AUC: 0.8408005890103077


| Metric          | Baseline |      Tuned |   Change |
| --------------- | -------: | ---------: | -------: |
| Accuracy        |   77.43% | **78.42%** |  ↑ 0.99% |
| Churn Precision |     0.57 |   **0.58** |   ↑ 0.01 |
| Churn Recall    |     0.62 |   **0.70** |   ↑ 0.08 |
| Churn F1        |     0.59 |   **0.63** |   ↑ 0.04 |
| ROC-AUC         |   0.8182 | **0.8408** | ↑ 0.0226 |


| Model             |   Accuracy | Churn Precision | Churn Recall | Churn F1 |   ROC-AUC |
| ----------------- | ---------: | --------------: | -----------: | -------: | --------: |
| Random Forest     |     74.24% |            0.51 |     **0.79** |     0.62 |     0.834 |
| Gradient Boosting |     76.86% |            0.55 |     **0.75** |     0.63 |     0.840 |
| **XGBoost**       | **78.42%** |        **0.58** |         0.70 | **0.63** | **0.841** |


# Logistic Regression Tuning

In [324]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score

best_f1 = float("-inf")
best_params = None

C_values = [0.01, 0.1, 1, 10, 100]

penalty_values = ["l1", "l2"]

solver_values = ["liblinear", "saga"]

max_iter_values = [1000, 2000]

for C in C_values:
    for penalty in penalty_values:
        for solver in solver_values:
            for max_iter in max_iter_values:

                # Skip invalid combinations
                if penalty == "l1" and solver not in ["liblinear", "saga"]:
                    continue

                if penalty == "l2" and solver not in ["liblinear", "saga"]:
                    continue

                lr = LogisticRegression(
                    C=C,
                    penalty=penalty,
                    solver=solver,
                    max_iter=max_iter,
                    random_state=42
                )

                lr.fit(
                    X_train_smote,
                    y_train_smote
                )

                y_pred = lr.predict(X_test_scaled)

                f1 = f1_score(
                    y_test,
                    y_pred
                )

                if f1 > best_f1:

                    best_f1 = f1

                    best_params = {
                        "C": C,
                        "penalty": penalty,
                        "solver": solver,
                        "max_iter": max_iter
                    }

                    print(
                        "C : ", C,
                        "penalty : ", penalty,
                        "solver : ", solver,
                        "max_iter : ", max_iter
                    )

print("Best F1 : ", best_f1)
print("Best Params : ", best_params)

C:\Users\syedz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\syedz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
C:\Users\syedz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\

C :  0.01 penalty :  l1 solver :  liblinear max_iter :  1000
C :  0.01 penalty :  l1 solver :  saga max_iter :  1000


C:\Users\syedz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\syedz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l

C :  10 penalty :  l1 solver :  liblinear max_iter :  1000


C:\Users\syedz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\syedz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
C:\Users\syedz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\

Best F1 :  0.6139438085327783
Best Params :  {'C': 10, 'penalty': 'l1', 'solver': 'liblinear', 'max_iter': 1000}


C:\Users\syedz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\syedz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l

In [325]:
best_lr = LogisticRegression(
    C=best_params["C"],
    penalty=best_params["penalty"],
    solver=best_params["solver"],
    max_iter=best_params["max_iter"],
    random_state=42
)

best_lr.fit(
    X_train_smote,
    y_train_smote
)

y_pred_best_lr = best_lr.predict(X_test_scaled)

C:\Users\syedz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\syedz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(


In [326]:
print("Accuracy:", accuracy_score(y_test, y_pred_best_lr))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_best_lr))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_best_lr))

print("\nROC-AUC:",
      roc_auc_score(
          y_test,
          best_lr.predict_proba(X_test_scaled)[:, 1]
      ))

Accuracy: 0.7366926898509581

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.72      0.80      1035
           1       0.50      0.79      0.61       374

    accuracy                           0.74      1409
   macro avg       0.70      0.75      0.71      1409
weighted avg       0.80      0.74      0.75      1409


Confusion Matrix:
[[743 292]
 [ 79 295]]

ROC-AUC: 0.8398718644242942


| Metric          | Baseline |      Tuned |      Change |
| --------------- | -------: | ---------: | ----------: |
| Accuracy        |   73.53% | **73.67%** |      +0.14% |
| Churn Precision |     0.50 |   **0.50** |   No change |
| Churn Recall    |     0.79 |   **0.79** |   No change |
| Churn F1        |     0.61 |   **0.61** | Almost same |
| ROC-AUC         |    0.840 |  **0.840** | Almost same |


# KNN hyperparameters

In [327]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score

best_f1 = float("-inf")
best_params = None

n_neighbors_values = [3, 5, 7, 9, 11]
weights_values = ["uniform", "distance"]
p_values = [1, 2]
leaf_size_values = [20, 30, 40]

for n_neighbors in n_neighbors_values:
    for weights in weights_values:
        for p in p_values:
            for leaf_size in leaf_size_values:

                knn = KNeighborsClassifier(
                    n_neighbors=n_neighbors,
                    weights=weights,
                    p=p,
                    leaf_size=leaf_size
                )

                knn.fit(
                    X_train_smote,
                    y_train_smote
                )

                y_pred = knn.predict(X_test_scaled)

                f1 = f1_score(
                    y_test,
                    y_pred
                )

                if f1 > best_f1:

                    best_f1 = f1

                    best_params = {
                        "n_neighbors": n_neighbors,
                        "weights": weights,
                        "p": p,
                        "leaf_size": leaf_size
                    }

                    print(
                        "n_neighbors : ", n_neighbors,
                        "weights : ", weights,
                        "p : ", p,
                        "leaf_size : ", leaf_size
                    )

print("Best F1 : ", best_f1)
print("Best Params : ", best_params)

n_neighbors :  3 weights :  uniform p :  1 leaf_size :  20
n_neighbors :  3 weights :  uniform p :  2 leaf_size :  20
n_neighbors :  5 weights :  uniform p :  1 leaf_size :  20
n_neighbors :  5 weights :  uniform p :  2 leaf_size :  20
n_neighbors :  7 weights :  uniform p :  1 leaf_size :  20
n_neighbors :  9 weights :  uniform p :  1 leaf_size :  20
n_neighbors :  9 weights :  uniform p :  2 leaf_size :  20
n_neighbors :  11 weights :  uniform p :  1 leaf_size :  20
Best F1 :  0.5759493670886076
Best Params :  {'n_neighbors': 11, 'weights': 'uniform', 'p': 1, 'leaf_size': 20}


In [328]:
best_knn = KNeighborsClassifier(
    n_neighbors=best_params["n_neighbors"],
    weights=best_params["weights"],
    p=best_params["p"],
    leaf_size=best_params["leaf_size"]
)

best_knn.fit(
    X_train_smote,
    y_train_smote
)

y_pred_best_knn = best_knn.predict(X_test_scaled)

In [329]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

print("Accuracy:", accuracy_score(y_test, y_pred_best_knn))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_best_knn))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_best_knn))

print("\nROC-AUC:",
      roc_auc_score(
          y_test,
          best_knn.predict_proba(X_test_scaled)[:, 1]
      ))

Accuracy: 0.7146912704045423

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.71      0.79      1035
           1       0.48      0.73      0.58       374

    accuracy                           0.71      1409
   macro avg       0.68      0.72      0.68      1409
weighted avg       0.77      0.71      0.73      1409


Confusion Matrix:
[[734 301]
 [101 273]]

ROC-AUC: 0.7915562272339766


### Current tuned models

| Model               |   Accuracy | Churn Precision | Churn Recall | Churn F1 |   ROC-AUC |
| ------------------- | ---------: | --------------: | -----------: | -------: | --------: |
| Random Forest       |     74.24% |            0.51 |         0.79 |     0.62 |     0.834 |
| Gradient Boosting   |     76.86% |            0.55 |         0.75 |     0.63 |     0.840 |
| XGBoost             | **78.42%** |        **0.58** |         0.70 | **0.63** | **0.841** |
| Logistic Regression |     73.67% |            0.50 |     **0.79** |     0.61 |     0.840 |
| KNN                 |     71.47% |            0.48 |         0.73 |     0.58 |     0.792 |


## Decision Tree Tuning

In [330]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score

best_f1 = float("-inf")
best_params = None

criterion_values = ["gini", "entropy", "log_loss"]
max_depth_values = [3, 5, 7, 10, None]
min_samples_split_values = [2, 5, 10]
min_samples_leaf_values = [1, 2, 4]
max_features_values = [None, "sqrt", "log2"]

for criterion in criterion_values:
    for max_depth in max_depth_values:
        for min_samples_split in min_samples_split_values:
            for min_samples_leaf in min_samples_leaf_values:
                for max_features in max_features_values:

                    dt = DecisionTreeClassifier(
                        criterion=criterion,
                        max_depth=max_depth,
                        min_samples_split=min_samples_split,
                        min_samples_leaf=min_samples_leaf,
                        max_features=max_features,
                        random_state=42
                    )

                    dt.fit(
                        X_train_smote,
                        y_train_smote
                    )

                    y_pred = dt.predict(X_test_scaled)

                    f1 = f1_score(
                        y_test,
                        y_pred
                    )

                    if f1 > best_f1:

                        best_f1 = f1

                        best_params = {
                            "criterion": criterion,
                            "max_depth": max_depth,
                            "min_samples_split": min_samples_split,
                            "min_samples_leaf": min_samples_leaf,
                            "max_features": max_features
                        }

                        print(
                            "criterion : ", criterion,
                            "max_depth : ", max_depth,
                            "min_samples_split : ", min_samples_split,
                            "min_samples_leaf : ", min_samples_leaf,
                            "max_features : ", max_features
                        )

print("Best F1 : ", best_f1)
print("Best Params : ", best_params)

criterion :  gini max_depth :  3 min_samples_split :  2 min_samples_leaf :  1 max_features :  None
criterion :  gini max_depth :  5 min_samples_split :  2 min_samples_leaf :  1 max_features :  None
Best F1 :  0.6105263157894737
Best Params :  {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': None}


In [331]:
best_dt = DecisionTreeClassifier(
    criterion=best_params["criterion"],
    max_depth=best_params["max_depth"],
    min_samples_split=best_params["min_samples_split"],
    min_samples_leaf=best_params["min_samples_leaf"],
    max_features=best_params["max_features"],
    random_state=42
)

best_dt.fit(
    X_train_smote,
    y_train_smote
)

y_pred_best_dt = best_dt.predict(X_test_scaled)

In [332]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

print("Accuracy:", accuracy_score(y_test, y_pred_best_dt))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_best_dt))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_best_dt))

print("\nROC-AUC:",
      roc_auc_score(
          y_test,
          best_dt.predict_proba(X_test_scaled)[:, 1]
      ))

Accuracy: 0.7636621717530163

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.79      0.83      1035
           1       0.54      0.70      0.61       374

    accuracy                           0.76      1409
   macro avg       0.71      0.74      0.72      1409
weighted avg       0.79      0.76      0.77      1409


Confusion Matrix:
[[815 220]
 [113 261]]

ROC-AUC: 0.8123885918003565


## Complete Baseline vs Tuned Comparison

| Model                              |   Accuracy | Churn Precision | Churn Recall | Churn F1 |   ROC-AUC |
| ---------------------------------- | ---------: | --------------: | -----------: | -------: | --------: |
| **Logistic Regression — Baseline** |     73.53% |            0.50 |         0.79 |     0.61 |     0.840 |
| **Logistic Regression — Tuned**    |     73.67% |            0.50 |     **0.79** |     0.61 |     0.840 |
| **KNN — Baseline**                 |     68.28% |            0.44 |         0.68 |     0.53 |     0.761 |
| **KNN — Tuned**                    |     71.47% |            0.48 |         0.73 |     0.58 |     0.792 |
| **Decision Tree — Baseline**       |     71.54% |            0.47 |         0.54 |     0.50 |     0.659 |
| **Decision Tree — Tuned**          | **76.37%** |            0.54 |         0.70 |     0.61 |     0.812 |
| **Random Forest — Baseline**       |     76.72% |            0.56 |         0.55 |     0.56 |     0.811 |
| **Random Forest — Tuned**          |     74.24% |            0.51 |     **0.79** |     0.62 |     0.834 |
| **Gradient Boosting — Baseline**   |     76.93% |            0.55 |         0.70 |     0.62 |     0.840 |
| **Gradient Boosting — Tuned**      |     76.86% |            0.55 |         0.75 |     0.63 |     0.840 |
| **XGBoost — Baseline**             |     77.43% |            0.57 |         0.62 |     0.59 |     0.818 |
| **XGBoost — Tuned**                | **78.42%** |        **0.58** |         0.70 | **0.63** | **0.841** |
